

















// Generated on 02/22/2023 19:13:45
using System;
using System.Collections.Generic;

namespace AmaknaProxy.API.Protocol.Enums
{

public enum ServerConnectionErrorEnum
{

SERVER_CONNECTION_ERROR_DUE_TO_STATUS = 0,
        SERVER_CONNECTION_ERROR_NO_REASON = 1,
        SERVER_CONNECTION_ERROR_ACCOUNT_RESTRICTED = 2,
        SERVER_CONNECTION_ERROR_SUBSCRIBERS_ONLY = 3,
        SERVER_CONNECTION_ERROR_REGULAR_PLAYERS_ONLY = 4,
        SERVER_CONNECTION_ERROR_MONOACCOUNT_CANNOT_VERIFY = 5,
        SERVER_CONNECTION_ERROR_MONOACCOUNT_ONLY = 6,
        SERVER_CONNECTION_ERROR_SERVER_OVERLOAD = 7,
        

}

}